[package]
name = "necsim-impls-cuda"
version = "0.1.0"
authors = ["Momo Langenstein <ml5717@ic.ac.uk>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core", features = ["cuda"] }

const-type-layout = { git = "https://github.com/MomoLangenstein/const-type-layout", rev = "7be4521" }
contracts = "0.6.3"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[target.'cfg(target_os = "cuda")'.dependencies]
rust-cuda = { git = "https://github.com/MomoLangenstein/rust-cuda", rev = "04a9e46", features = ["derive"] }

[target.'cfg(not(target_os = "cuda"))'.dependencies]
rust-cuda = { git = "https://github.com/MomoLangenstein/rust-cuda", rev = "04a9e46", features = ["derive", "host"] }
