[package]
name = "necsim-impls-cuda"
version = "0.1.0"
authors = ["Moritz Langenstein <ml5717@ic.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../../necsim/core", features = ["cuda"] }
contracts = "0.6.0"

rust-cuda-derive = { path = "../../../rust-cuda/rust-cuda-derive" }
rustacuda_core = { version = "0.1.2" }

[target.'cfg(target_os = "cuda")'.dependencies]
rust-cuda = { path = "../../../rust-cuda", features = [] }

[target.'cfg(not(target_os = "cuda"))'.dependencies]
rust-cuda = { path = "../../../rust-cuda", features = ["host"] }
rustacuda = { version = "0.1.2" }
