image:
  file: .gitpod.Dockerfile

tasks:
  - init: >-
      cargo install ptx-linker -f && cargo install cargo-mpirun -f && ./setup.sh
      && cargo fmt && cargo clippy --all-features && cargo build --all-features

vscode:
  extensions:
    - bungcip.better-toml
    - serayuzgur.crates
    - a5huynh.vscode-ron
    - matklad.rust-analyzer

github:
  prebuilds:
    # enable for the main/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
