
image:
  file: .gitpod.Dockerfile

tasks:
  - init: cargo install ptx-linker -f && cargo install cargo-mpirun -f && cd necsim/linker && cargo build --release && cd ../..

vscode:
  extensions:
    - bungcip.better-toml
    - serayuzgur.crates
    - a5huynh.vscode-ron
    - matklad.rust-analyzer
