[workspace]

members = [
    "necsim-core",
    "necsim-impls-std",
    "necsim-impls-no-std",
    "necsim-classical",
    "necsim-gillespie",
    "necsim-skipping-gillespie",
    "rustcoalescence",
    "rust-cuda-test",
    "rust-cuda-test/kernel",
    "float-next-after-no-std",
]

[profile.dev]
opt-level = 3
lto = "fat"

[profile.release]
opt-level = 3
lto = "fat"
