[workspace]

members = [
    "necsim/core",
    "necsim/core/bond",

    "necsim/impls/no-std",
    "necsim/impls/std",
    "necsim/impls/cuda",

    "necsim/plugins/core",
    "necsim/plugins/common",
    "necsim/plugins/csv",
    "necsim/plugins/metacommunity",
    "necsim/plugins/statistics",
    "necsim/plugins/species",
    "necsim/plugins/demo",

    "necsim/partitioning/core",
    "necsim/partitioning/monolithic",
    "necsim/partitioning/mpi",

    "rustcoalescence",

    "rustcoalescence/linker",

    "rustcoalescence/scenarios",

    "rustcoalescence/algorithms",
    "rustcoalescence/algorithms/monolithic",
    "rustcoalescence/algorithms/independent",
    "rustcoalescence/algorithms/cuda",
    "rustcoalescence/algorithms/cuda/kernel",
    "rustcoalescence/algorithms/cuda/kernel/specialiser",
    "rustcoalescence/algorithms/cuda/kernel/ptx-jit",

    "rust-cuda",
    "rust-cuda/rust-cuda-derive",

    "analysis/rng/randomness",
    "analysis/rng/hash",
    "analysis/rng/correlation",
    "analysis/performance/exponential",
    "analysis/performance/exponential/kernel",
    "analysis/performance/reporting",
]

default-members = [
    "rustcoalescence",
    
    "necsim/plugins/common",
    "necsim/plugins/csv",
    "necsim/plugins/metacommunity",
    "necsim/plugins/statistics",
    "necsim/plugins/species",
    "necsim/plugins/demo",
]

[patch.crates-io]
array2d = { path = "third-party/array2d-no-std" }
float_next_after = { path = "third-party/float-next-after-no-std" }
ptx-builder = { path = "third-party/rust-ptx-builder" }
rustacuda = { path = "third-party/RustaCUDA" }
rustacuda_core = { path = "third-party/RustaCUDA/rustacuda_core" }
rustacuda_derive = { path = "third-party/RustaCUDA/rustacuda_derive" }
mpi = { git = "https://github.com/rsmpi/rsmpi", rev = "e9b1844" }
contracts = { path = "third-party/contracts" }
ron = { path = "third-party/ron" }

[profile.release]
opt-level = 3
lto = "fat"
