[workspace]

members = [
    "rustcoalescence",

    "necsim/core",
    
    "necsim/impls/std",
    "necsim/impls/no-std",
    "necsim/impls/cuda",

    "necsim/algorithms/classical",
    "necsim/algorithms/gillespie",
    "necsim/algorithms/skipping-gillespie",
    "necsim/algorithms/cuda",
    "necsim/algorithms/cuda/kernel",
    "necsim/algorithms/cuda/kernel/specialiser",

    "necsim/linker",

    "rust-cuda",
    "rust-cuda/rust-cuda-derive",

    #"third-party/float-next-after-no-std",
    #"third-party/rust-ptx-builder",
    #"third-party/array2d-no-std",    
]

[patch.crates-io]
array2d = { path = "third-party/array2d-no-std" }
float_next_after = { path = "third-party/float-next-after-no-std" }
ptx-builder = { path = "third-party/rust-ptx-builder" }

[profile.dev]
opt-level = 3
lto = "fat"

[profile.release]
opt-level = 3
lto = "fat"
