[workspace]

members = [
    "necsim-core",
    "necsim-impls",
    "necsim-classical",
    "necsim-gillespie",
    "necsim-skipping-gillespie",
    "rustcoalescence",
]

[profile.dev]
opt-level = 3
lto = "fat"

[profile.release]
opt-level = 3
lto = "fat"
