[workspace]

members = [
    "float-next-after-no-std",
    "rust-ptx-builder",
    "array2d-no-std",

    "rust-cuda",
    "rust-cuda/rust-cuda-derive",

    "necsim-core",
    "necsim-impls-std",
    "necsim-impls-no-std",
    "necsim-impls-cuda",

    "necsim-classical",
    "necsim-gillespie",
    "necsim-skipping-gillespie",
    "necsim-cuda",
    "necsim-cuda/kernel",

    "necsim-config",

    "rustcoalescence",
]

[profile.dev]
opt-level = 3
lto = "fat"

[profile.release]
opt-level = 3
lto = "fat"
