[workspace]

members = [
    "rustcoalescence",

    "necsim/core",
    
    "necsim/impls/std",
    "necsim/impls/no-std",
    "necsim/impls/cuda",
    "necsim/impls/mpi",

    "necsim/scenarios",

    "necsim/algorithms",
    "necsim/algorithms/monolithic",
    "necsim/algorithms/independent",
    "necsim/algorithms/cuda",
    "necsim/algorithms/cuda/kernel",
    "necsim/algorithms/cuda/kernel/specialiser",
    "necsim/algorithms/cuda/kernel/ptx-jit",

    "necsim/plugins/core",
    "necsim/plugins/common",
    "necsim/plugins/csv",
    "necsim/plugins/coalescence",
    "necsim/plugins/metacommunity",

    "necsim/linker",

    "rust-cuda",
    "rust-cuda/rust-cuda-derive",
]

default-members = [
    "rustcoalescence",
    
    "necsim/plugins/common",
    "necsim/plugins/csv",
    "necsim/plugins/metacommunity",
]

[patch.crates-io]
array2d = { path = "third-party/array2d-no-std" }
float_next_after = { path = "third-party/float-next-after-no-std" }
ptx-builder = { path = "third-party/rust-ptx-builder" }
type-layout = { path = "third-party/type-layout" }
tynm = { path = "third-party/tynm" }
memoffset = { path = "third-party/memoffset" }
rustacuda = { path = "third-party/RustaCUDA" }
rustacuda_core = { path = "third-party/RustaCUDA/rustacuda_core" }
rustacuda_derive = { path = "third-party/RustaCUDA/rustacuda_derive" }
mpi = { git = "https://github.com/rsmpi/rsmpi", rev = "e9b1844" }
slab = { git = "https://github.com/tokio-rs/slab.git", rev = "57f69fd" }
contracts = { path = "third-party/contracts" }
ron = { path = "third-party/ron" }

[profile.release]
opt-level = 3
lto = "fat"
