[package]
name = "array2d"
version = "0.2.1"
authors = ["Harrison McCullough <mccullough.harrison@gmail.com>"]
edition = "2018"
description = "A fixed sized two-dimensional array"
readme = "README.md"
license = "MIT"
repository = "https://github.com/HarrisonMc555/array2d"

[features]
default = []
cuda = ["rust-cuda"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[target.'cfg(target_os = "cuda")'.dependencies]
rust-cuda = { path = "../../rust-cuda", features = ["derive"], optional = true }

[target.'cfg(not(target_os = "cuda"))'.dependencies]
rust-cuda = { path = "../../rust-cuda", features = ["derive", "host"], optional = true }
