[package]
name = "kernel"
version = "0.1.0"
authors = ["Momo Langenstein <ml5717@ic.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../../core", features = ["cuda"] }
rust-cuda = { path = "../../../../rust-cuda", features = [] }
necsim-impls-no-std = { path = "../../../impls/no-std", features = ["cuda"] }
necsim-impls-cuda = { path = "../../../impls/cuda" }
rustacuda_core = "0.1.2"
specialiser = { path = "./specialiser" }
ptx-jit = { path = "./ptx-jit" }

[build-dependencies]
specialiser = { path = "./specialiser" }
