[package]
name = "necsim-impls-mpi"
version = "0.1.0"
authors = ["Moritz Langenstein <ml5717@ic.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contracts = "0.6.0"
mpi = { version = "0.6.0", default-features = false, features = ["derive"] }
thiserror = "1.0"

necsim-core = { path = "../../core", features = ["mpi"] }
necsim-impls-no-std = { path = "../no-std" }
necsim-impls-std = { path = "../std" }
