[package]
name = "linked-hash-map"
version = "0.5.4"
license = "MIT/Apache-2.0"
description = "A HashMap wrapper that holds key-value pairs in insertion order"
authors = [
    "Stepan Koltsov <stepan.koltsov@gmail.com>",
    "Andrew Paseltiner <apaseltiner@gmail.com>",
]
edition = "2018"

repository = "https://github.com/contain-rs/linked-hash-map"
homepage = "https://github.com/contain-rs/linked-hash-map"
documentation = "https://docs.rs/linked-hash-map"
keywords = ["data-structures"]
readme = "README.md"
exclude = ["/.travis.yml", "/deploy-docs.sh"]

[dependencies]
slab = "0.4.2"
