[package]
name = "lru-set"
version = "0.5.4"
license = "MIT/Apache-2.0"
description = "A LRU set that holds a maximum number of values in insertion order"
authors = [
    "Stepan Koltsov <stepan.koltsov@gmail.com>",
    "Andrew Paseltiner <apaseltiner@gmail.com>",
]
edition = "2018"

keywords = ["data-structures"]
readme = "README.md"
