[package]
name = "necsim-partitioning-core"
version = "0.1.0"
authors = ["Momo Langenstein <ml5717@ic.ac.uk>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core" }
necsim-core-bond = { path = "../../core/bond" }

anyhow = { version = "1.0", default-features = false }
contracts = { git = "https://gitlab.com/MomoLangenstein/contracts", rev = "3a44375a" }
