[package]
name = "necsim-algorithms-independent"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core" }
necsim-impls-no-std = { path = "../../impls/no-std" }
necsim-impls-std = { path = "../../impls/std" }
necsim-scenarios = { path = "../../scenarios" }
necsim-algorithms = { path = "../" }

serde = { version = "1.0", features = ["derive"] }
serde_state = "0.4.8"
serde_derive_state = "0.4.8"
