[package]
name = "necsim-independent"
version = "0.1.0"
authors = ["Moritz Langenstein <moritz.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../../necsim/core" }
necsim-impls-no-std = { path = "../../../necsim/impls/no-std" }
necsim-impls-std = { path = "../../../necsim/impls/std" }
array2d = "0.2.1"
anyhow = "1.0"
contracts = "0.6.0"
lru-set = "0.5.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
serde_state = "0.4.8"
