[package]
name = "necsim-classical"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core" }
necsim-impls-no-std = { path = "../../impls/no-std" }
necsim-impls-std = { path = "../../impls/std" }

array2d = "0.2.1"
anyhow = "1.0"
contracts = "0.6.0"
