[build]
pipelining = false

[target.nvptx64-nvidia-cuda]
rustflags = ["-Clink-args=--arch=sm_35", "-Cpanic=abort", "-Clinker-plugin-lto", "-Ccodegen-units=1", "-Clink-arg=-Olto"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]
features = ["all"]
configurable-env = true

[env]
NECSIM_CORE_F64_LINK_LN = "nvptx_ln"
NECSIM_CORE_F64_LINK_EXP = "nvptx_exp"
NECSIM_CORE_F64_LINK_SIN = "nvptx_sin"
NECSIM_CORE_F64_LINK_COS = "nvptx_cos"
NECSIM_CORE_F64_LINK_ROUND = "nvptx_round"
