[package]
name = "necsim-partitioning-monolithic"
version = "0.1.0"
authors = ["Juniper Tyree <juniper.tyree@helsinki.fi>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core" }
necsim-core-bond = { path = "../../core/bond" }
necsim-impls-std = { path = "../../impls/std" }
necsim-partitioning-core = { path = "../core" }

anyhow = { version = "1.0", default-features = false }
contracts = "0.6.3"
serde = "1.0"
