[package]
name = "necsim-core"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
cuda = ["rust-cuda", "rustacuda_core", "rustacuda_derive"]

[dependencies]
necsim-core-f64 = { path = "f64" }
necsim-core-bond = { path = "bond" }

contracts = { git = "https://gitlab.com/MomoLangenstein/contracts", rev = "3a44375a" }
typed-builder = "0.9"
serde = { version = "1.0", default-features = false, features = ["derive"] }

default-env = "0.1"

rustacuda_core = { version = "0.1.2", optional = true }
rustacuda_derive = { version = "0.1.2", optional = true }

[target.'cfg(target_os = "cuda")'.dependencies]
rust-cuda = { git = "https://github.com/MomoLangenstein/rust-cuda", rev = "22368c2", features = ["derive"], optional = true }

[target.'cfg(not(target_os = "cuda"))'.dependencies]
rust-cuda = { git = "https://github.com/MomoLangenstein/rust-cuda", rev = "22368c2", features = ["derive", "host"], optional = true }
