[package]
name = "necsim-core"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
cuda = ["rust-cuda", "rust-cuda-derive", "rustacuda_core", "rustacuda_derive", "rustacuda"]
# mpi = ["mpi"]

[dependencies]
necsim-core-bond = { path = "bond" }

contracts = "0.6"
typed-builder = "0.9.0"
type-layout = "0.2.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }

rust-cuda-derive = { path = "../../rust-cuda/rust-cuda-derive", optional = true }
rustacuda_core = { version = "0.1.2", optional = true }
rustacuda_derive = { version = "0.1.2", optional = true }

mpi = { version = "0.6.0", default-features = false, features = ["derive"], optional = true }

[target.'cfg(target_os = "cuda")'.dependencies]
rust-cuda = { path = "../../rust-cuda", features = [], optional = true }

[target.'cfg(not(target_os = "cuda"))'.dependencies]
rust-cuda = { path = "../../rust-cuda", features = ["host"], optional = true }
rustacuda = { version = "0.1.2", optional = true }
