[build]
pipelining = false

[target.nvptx64-nvidia-cuda]
rustflags = ["-Zunstable-options", "-Clinker-flavor=llbc", "-Ctarget-cpu=sm_35", "-Cpanic=abort", "-Ccodegen-units=1", "-Clink-arg=-O3"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]
features = ["all"]
