[package]
name = "necsim-partitioning-mpi"
version = "0.1.0"
authors = ["Juniper Tyree <juniper.langenstein@helsinki.fi>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core" }
necsim-core-bond = { path = "../../core/bond" }
necsim-impls-std = { path = "../../impls/std" }
necsim-partitioning-core = { path = "../../partitioning/core" }

contracts = "0.6.3"
mpi = { git = "https://github.com/juntyr/rsmpi", rev = "68c1df5", version = "0.6", default-features = false, features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
memoffset = "0.8"
serde = "1.0"
serde_state = "0.4"
serde_derive_state = "0.4"
humantime-serde = "1.1"

[build-dependencies]
build-probe-mpi = "0.1"
