[package]
name = "necsim-core-bond"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
cuda = ["rustacuda_core", "rustacuda_derive"]
# mpi = ["mpi"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
float_next_after = "0.1.5"

rustacuda_core = { version = "0.1.2", optional = true }
rustacuda_derive = { version = "0.1.2", optional = true }

mpi = { version = "0.6.0", default-features = false, features = ["derive"], optional = true }