[package]
name = "necsim-core-bond"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
necsim-core-maths = { path = "../maths" }

const-type-layout = { git = "https://github.com/MomoLangenstein/const-type-layout", rev = "b675e0c" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
