[package]
name = "necsim-core-bond"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
cuda = ["rustacuda_core", "rustacuda_derive"]
# mpi = ["mpi"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
float_next_after = { path = "../../../third-party/float-next-after-no-std" }

rustacuda_core = { version = "0.1.2", optional = true }
rustacuda_derive = { version = "0.1.2", optional = true }

mpi = { git = "https://github.com/rsmpi/rsmpi", rev = "e9b1844", default-features = false, features = ["derive"], optional = true }
