[package]
name = "necsim-core-bond"
version = "0.1.0"
authors = ["Juniper Tyree <juniper.tyree@helsinki.fi>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
necsim-core-maths = { path = "../maths" }

const-type-layout = { git = "https://github.com/juntyr/const-type-layout", rev = "645de0e" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
