[package]
name = "necsim-impls-no-std"
version = "0.1.0"
authors = ["Momo Langenstein <ml5717@ic.ac.uk>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
cuda = ["rust-cuda", "necsim-core/cuda"]

[dependencies]
necsim-core = { path = "../../core" }
necsim-core-maths = { path = "../../core/maths" }
necsim-core-bond = { path = "../../core/bond" }
necsim-partitioning-core = { path = "../../partitioning/core" }

const-type-layout = { git = "https://github.com/MomoLangenstein/const-type-layout", rev = "aa5ad03" }
contracts = "0.6.3"
libm = "0.2"
hashbrown = "0.13"
slab = { version = "0.4", default-features = false, features = [] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
log = "0.4"
displaydoc = { version = "0.2", default-features = false, features = [] }
final = "0.1.1"
fnv = { version = "1.0", default-features = false, features = [] }
rand_core = "0.6"

[target.'cfg(target_os = "cuda")'.dependencies]
rust-cuda = { git = "https://github.com/MomoLangenstein/rust-cuda", rev = "0befd6d", features = ["derive"], optional = true }

[target.'cfg(not(target_os = "cuda"))'.dependencies]
rust-cuda = { git = "https://github.com/MomoLangenstein/rust-cuda", rev = "0befd6d", features = ["derive", "host"], optional = true }
