[package]
name = "necsim-impls-no-std"
version = "0.1.0"
authors = ["Momo Langenstein <ml5717@ic.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
cuda = ["rust-cuda", "rust-cuda-derive", "rustacuda_core", "rustacuda_derive", "rustacuda", "array2d/cuda", "necsim-core/cuda"]

[dependencies]
necsim-core = { path = "../../core" }
necsim-core-bond = { path = "../../core/bond" }

array2d = "0.2.1"
contracts = "0.6.0"
nanorand = { version = "0.5.2", default-features = false, features = ["wyrand"] }
aes = { version = "0.7.0", default-features = false, features = ["force-soft"] }
wyhash = "0.5.0"
seahash = "4.1.0"
libm = "0.2.1"
hashbrown = "0.11.2"
xxhash-rust = { version = "0.8.2", features = ["xxh64"] }
slab = { version = "0.4.3", default-features = false, features = [] }
anyhow = { version = "1.0", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }

rust-cuda-derive = { path = "../../../rust-cuda/rust-cuda-derive", optional = true }
rustacuda_core = { version = "0.1.2", optional = true }
rustacuda_derive = { version = "0.1.2", optional = true }

[target.'cfg(target_os = "cuda")'.dependencies]
rust-cuda = { path = "../../../rust-cuda", features = [], optional = true }

[target.'cfg(not(target_os = "cuda"))'.dependencies]
rust-cuda = { path = "../../../rust-cuda", features = ["host"], optional = true }
rustacuda = { version = "0.1.2", optional = true }
