[package]
name = "necsim-impls-std"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core" }
necsim-impls-no-std = { path = "../../impls/no-std" }
array2d = "0.2.1"
thiserror = "1.0"
contracts = "0.6.0"
float_next_after = "0.1.5"
priority-queue = "1.0"
rand = "0.8.3"
anyhow = "1.0"
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
pcg_rand = "0.13.0"
log = { version = "0.4.14", features = ["std"] }
