[package]
name = "necsim-impls-std"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core" }
necsim-core-bond = { path = "../../core/bond" }
necsim-impls-no-std = { path = "../../impls/no-std" }

thiserror = "1.0"
contracts = { git = "https://gitlab.com/MomoLangenstein/contracts", rev = "3a44375a" }
rand_core = "0.6"
anyhow = "1.0"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
pcg_rand = { version = "0.13", features = ["u128", "serde1"] }
glob = "0.3"
