[package]
name = "rustcoalescence"
version = "0.1.0"
authors = ["Moritz Langenstein <moritz.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
necsim-mpi = ["necsim-impls-mpi"]

[dependencies]
necsim-core = { path = "../necsim/core" }
necsim-impls-no-std = { path = "../necsim/impls/no-std" }
necsim-impls-std = { path = "../necsim/impls/std" }
array2d = "0.2.1"
structopt = "0.3.21"
anyhow = "1.0"
contracts = "0.6.0"
derive-getters = "0.2.0"
tiff = "0.6"
serde = { version = "1.0", features = ["derive"] }
ron = "0.6.4"

necsim-classical = { path = "../necsim/algorithms/classical", optional = true }
necsim-gillespie = { path = "../necsim/algorithms/gillespie", optional = true }
necsim-skipping-gillespie = { path = "../necsim/algorithms/skipping-gillespie", optional = true }
necsim-cuda = { path = "../necsim/algorithms/cuda", optional = true }
necsim-independent = { path = "../necsim/algorithms/independent", optional = true }
necsim-impls-mpi = { path = "../necsim/impls/mpi", optional = true }
