[package]
name = "rustcoalescence"
version = "0.1.0"
authors = ["Moritz Langenstein <moritz.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../necsim-core" }
necsim-impls-no-std = { path = "../necsim-impls-no-std" }
necsim-impls-std = { path = "../necsim-impls-std" }
necsim-classical = { path = "../necsim-classical" }
necsim-gillespie = { path = "../necsim-gillespie" }
necsim-skipping-gillespie = { path = "../necsim-skipping-gillespie" }
necsim-cuda = { path = "../necsim-cuda" }
rand = "0.7.3"
array2d = { path = "../array2d-no-std" }
structopt = "0.3.20"
gdal = { version = "0.6.0", features = ["bindgen"] }
anyhow = "1.0"
contracts = "0.6.0"
cast = "0.2.3"
derive-getters = "0.2.0"
