[package]
name = "rustcoalescence"
version = "0.1.0"
authors = ["Moritz Langenstein <moritz.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"
structopt = "0.3.20"
necsim = { path = "../necsim" }
gdal = "0.6.0"
