[package]
name = "rustcoalescence"
version = "0.1.0"
authors = ["Moritz Langenstein <moritz.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../necsim-core" }
necsim-impls = { path = "../necsim-impls" }
necsim-classical = { path = "../necsim-classical" }
necsim-gillespie = { path = "../necsim-gillespie" }
rand = "0.7.3"
array2d = "0.2.1"
structopt = "0.3.20"
gdal = "0.6.0"
anyhow = "1.0.33"
contracts = "0.6.0"
cast = "0.2.3"
