[package]
name = "rustcoalescence"
version = "0.1.0"
authors = ["Moritz Langenstein <moritz.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-corev2 = { path = "../necsim-corev2" }
necsim-implsv2 = { path = "../necsim-implsv2" }
necsim-classical = { path = "../necsim-classical" }
necsim-gillespie = { path = "../necsim-gillespie" }
necsim-skipping-gillespie = { path = "../necsim-skipping-gillespie" }
rand = "0.7.3"
array2d = "0.2.1"
structopt = "0.3.20"
gdal = "0.6.0"
anyhow = "1.0.33"
contracts = "0.6.0"
cast = "0.2.3"
derive-getters = "0.2.0"
