[package]
name = "ptx-jit"
version = "0.1.0"
authors = ["Momo Langenstein <ml5717@ic.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(target_os = "cuda"))'.dependencies]
regex = "1.4.3"
lazy_static = "1.4.0"
