[package]
name = "necsim-cuda"
version = "0.1.0"
authors = ["Momo Langenstein <ml5717@ic.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core", features = ["cuda"] }
necsim-impls-no-std = { path = "../../impls/no-std", features = ["cuda"] }
necsim-impls-std = { path = "../../impls/std" }
necsim-impls-cuda = { path = "../../impls/cuda" }
kernel = { path = "./kernel" }
ptx-jit = { path = "./kernel/ptx-jit" }

array2d = "0.2.1"
anyhow = "1.0"
contracts = "0.6.0"
rust-cuda = { path = "../../../rust-cuda", features = ["host"] }
rustacuda = "0.1.2"
rustacuda_core = "0.1.2"
bitvec = "0.22"
type-layout = "0.2.0"
lru-set = "0.5.4"
serde = { version = "1.0", features = ["derive"] }
