[package]
name = "necsim-algorithms-cuda"
version = "0.1.0"
authors = ["Momo Langenstein <momo.langenstein17@imperial.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
necsim-core = { path = "../../core" }
necsim-impls-no-std = { path = "../../impls/no-std" }
necsim-impls-std = { path = "../../impls/std" }
necsim-impls-cuda = { path = "../../impls/cuda" }
necsim-scenarios = { path = "../../scenarios" }
necsim-algorithms = { path = "../" }
necsim-algorithms-cuda-kernel = { path = "./kernel" }
necsim-algorithms-cuda-kernel-ptx-jit = { path = "./kernel/ptx-jit" }

anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_state = "0.4.8"
serde_derive_state = "0.4.8"
contracts = "0.6.0"
rust-cuda = { path = "../../../rust-cuda", features = ["host"] }
rustacuda = "0.1.2"
rustacuda_core = "0.1.2"
bitvec = "0.22"
type-layout = "0.2.0"
