name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * MON'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.14
        with:
          method: network
          use-github-cache: false
          use-local-cache: false

      - name: Install OpenMPI
        run: |
          sudo apt-get update -q
          sudo apt-get install libopenmpi-dev -y --no-install-recommends

      - name: Install the rust-ptx-linker
        run: |
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh
          sudo ./llvm.sh $(rustc --version -v | grep -oP "LLVM version: \K\d+")
          rm llvm.sh
          cargo install rust-ptx-linker --git https://github.com/juntyr/rust-ptx-linker --force
      
      - name: Check the default features
        run: cargo check
      
      - name: Check all features
        run: cargo check --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.14
        with:
          method: network
          use-github-cache: false
          use-local-cache: false
      
      - name: Install OpenMPI
        run: |
          sudo apt-get update -q
          sudo apt-get install libopenmpi-dev -y --no-install-recommends

      - name: Install the rust-ptx-linker
        run: |
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh
          sudo ./llvm.sh $(rustc --version -v | grep -oP "LLVM version: \K\d+")
          rm llvm.sh
          cargo install rust-ptx-linker --git https://github.com/juntyr/rust-ptx-linker --force
      
      - name: Run the test-suite
        run: cargo test --workspace --no-fail-fast

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Check the code formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.14
        with:
          method: network
          use-github-cache: false
          use-local-cache: false

      - name: Install OpenMPI
        run: |
          sudo apt-get update -q
          sudo apt-get install libopenmpi-dev -y --no-install-recommends

      - name: Install the rust-ptx-linker
        run: |
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh
          sudo ./llvm.sh $(rustc --version -v | grep -oP "LLVM version: \K\d+")
          rm llvm.sh
          cargo install rust-ptx-linker --git https://github.com/juntyr/rust-ptx-linker --force

      - name: Check the code style for the default features
        run: cargo clippy -- -D warnings
      
      - name: Check the code style for all features
        run: cargo clippy --all-features -- -D warnings
