name: Code Coverage

on: [push]

jobs:
  test:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install the Rust toolchain
        run: cargo && rustup component add llvm-tools-preview
        
      - name: Generate the code coverage
        run: |
          export RUSTFLAGS="-Zinstrument-coverage"

          cargo build

          LLVM_PROFILE_FILE="codecov-%p-%m.profraw" cargo test \
            --workspace \
            --exclude array2d \
            --exclude contracts \
            --exclude contracts \
            --exclude float_next_after \
            --exclude ron \
            --exclude ptx-builder \
            --exclude rustacuda \
            --exclude rustacuda_core \
            --exclude rustacuda_derive
          
          grcov . -s . --binary-path ./target/debug/ \
            -t cobertura -o cobertura.xml --branch \
            --keep-only "necsim/*" \
            --keep-only "rust-cuda/*" \
            --keep-only "rustcoalescence/*" \
            --ignore-not-existing \
            --excl-line GRCOV_EXCL_LINE \
            --excl-start GRCOV_EXCL_START \
            --excl-stop GRCOV_EXCL_STOP

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
