name: rebase demo
on:
  push:
    branches:
      - main

jobs:
  rebase:
    name: Rebase the demo branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEMO_AUTO_REBASE_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.DEMO_AUTO_REBASE_TOKEN }}
