name: rustdoc to gh-pages

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install OpenMPI
        run: |
          sudo apt-get update -q
          sudo apt-get install libopenmpi-dev -y --no-install-recommends

      - name: Install the Rust toolchain
        run: cargo install ptx-linker --force --locked

      - name: Build the Documentation
        run: |
          RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo doc \
            --workspace --no-deps --all-features

      - name: Deploy the Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.RUSTDOC_DEPLOY_KEY }}
          external_repository: MomoLangenstein/necsim-rust-docs
          publish_branch: gh-pages
          publish_dir: ./target/doc
